"""2026 NFL regular-season schedule, as "AWAY HOME" pairs by week.

Weeks 1-4 are also in the score strings on the site pages. International games
list the designated home team second; the model treats them as neutral sites.
Checked by tools/check_schedule.py.
"""

WEEKS = {
    1: "BUF HOU,TB CIN,CLE JAX,NE SEA,MIA LV,GB MIN,BAL IND,WAS PHI,ATL PIT,NYJ TEN,NO DET,DEN KC,DAL NYG,CHI CAR,ARI LAC,SF LAR",
    2: "DET BUF,PHI TEN,PIT NE,MIN CHI,CAR ATL,GB NYJ,NO BAL,CIN HOU,CLE TB,JAX DEN,LV LAC,SEA ARI,MIA SF,WAS DAL,IND KC,NYG LAR",
    3: "ATL GB,HOU IND,KC MIA,LAC BUF,TEN NYG,CIN PIT,SEA WAS,NE JAX,CAR CLE,NYJ DET,ARI SF,MIN TB,LV NO,BAL DAL,LAR DEN,PHI CHI",
    4: "PIT CLE,IND WAS,NE BUF,ARI NYG,NYJ CHI,TEN BAL,GB TB,DAL HOU,JAX CIN,LAR PHI,MIA MIN,DEN SF,LAC SEA,KC LV,DET CAR,ATL NO",
    5: "TB DAL,PHI JAX,CHI GB,HOU TEN,CIN MIA,LV NE,MIN NO,CLE NYJ,IND PIT,NYG WAS,DEN LAC,DET ARI,SF SEA,BAL ATL,BUF LAR",
    6: "SEA DEN,HOU JAX,NYJ NE,PIT TB,CAR PHI,CHI ATL,TEN IND,NO NYG,BAL CLE,ARI LAR,LAC KC,BUF LV,DAL GB,WAS SF",
    7: "NE CHI,PIT NO,CLE TEN,MIA NYJ,IND MIN,CIN BAL,NYG HOU,TB CAR,SF ATL,DEN ARI,LAR LV,GB DET,KC SEA,DAL PHI",
    8: "CAR GB,TEN CIN,IND JAX,CLE PIT,BAL BUF,ATL TB,MIN DET,ARI DAL,LV NYJ,LAC LAR,KC DEN,NE MIA,PHI WAS,CHI SEA",
    9: "JAX BAL,CIN ATL,NYJ KC,CLE NO,DEN CAR,DAL IND,DET MIA,NYG PHI,LAR WAS,LV SF,HOU LAC,ARI SEA,GB NE,TB CHI,BUF MIN",
    10: "WAS NYG,NE DET,CAR NO,HOU CLE,BUF NYJ,MIA IND,JAX TEN,KC ATL,MIN GB,SEA LV,LAR ARI,SF DAL,PIT CIN,LAC BAL",
    11: "IND HOU,BAL CAR,NO CHI,TB DET,MIA BUF,JAX NYG,TEN DAL,ARI KC,NYJ LAC,PIT PHI,LV DEN,MIN SF,CIN WAS",
    12: "GB LAR,CHI DET,PHI DAL,KC BUF,DEN PIT,NO CIN,BAL HOU,NYG IND,LV CLE,ATL MIN,NYJ MIA,TEN JAX,SEA SF,WAS ARI,NE LAC,CAR TB",
    13: "KC LAR,SF NYG,JAX CHI,CIN CLE,LAC TB,DET ATL,GB NO,WAS TEN,PHI ARI,MIA DEN,BUF NE,CAR MIN,HOU PIT,DAL SEA",
    14: "MIN NE,NO CAR,CHI MIA,TB BAL,TEN DET,HOU WAS,IND PHI,ATL CLE,DEN NYJ,LAC LV,NYG SEA,LAR SF,KC CIN,BUF GB,PIT JAX",
    15: "SF LAC,SEA PHI,CHI BUF,CIN CAR,NO TB,JAX HOU,IND TEN,BAL PIT,CLE NYG,ATL WAS,MIA GB,NYJ ARI,DAL LAR,DEN LV,DET MIN,NE KC",
    16: "HOU PHI,GB CHI,BUF DEN,LAR SEA,CLE BAL,LAC MIA,ARI NO,NE NYJ,TEN LV,SF KC,JAX DAL,NYG DET,TB ATL,CAR PIT,CIN IND,WAS MIN",
    17: "BAL CIN,NO ATL,IND CLE,NYG DAL,PIT TEN,BUF MIA,MIN NYJ,SEA CAR,LV ARI,DET CHI,PHI SF,DEN NE,WAS JAX,KC LAC,LAR TB,HOU GB",
    18: "SEA LAR,MIA NE,SF ARI,ATL CAR,CHI MIN,CLE CIN,TB NO,DET GB,TEN HOU,NYJ BUF,JAX IND,PIT BAL,LAC DEN,LV KC,PHI NYG,DAL WAS",
}

# International games (neutral site for the model): week -> set of (away, home)
NEUTRAL = {
    4: {("IND", "WAS")},          # London
    5: {("PHI", "JAX")},          # London
    6: {("HOU", "JAX")},          # London
    7: {("PIT", "NO")},           # Paris
    9: {("CIN", "ATL")},          # Madrid
    10: {("NE", "DET")},          # 9:30 a.m. ET game
}

DIVISIONS = {
    "AFC East": ["BUF", "MIA", "NE", "NYJ"], "AFC North": ["BAL", "CIN", "CLE", "PIT"],
    "AFC South": ["HOU", "IND", "JAX", "TEN"], "AFC West": ["DEN", "KC", "LV", "LAC"],
    "NFC East": ["DAL", "NYG", "PHI", "WAS"], "NFC North": ["CHI", "DET", "GB", "MIN"],
    "NFC South": ["ATL", "CAR", "NO", "TB"], "NFC West": ["ARI", "LAR", "SF", "SEA"],
}


def games():
    """[(week, away, home)] for the whole season."""
    return [(w, *g.split()) for w, s in WEEKS.items() for g in s.split(",")]
